/*
 * Copyright (C) 2023-2024 The RisingOS Android Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.systemui.theme;

import android.provider.Settings;

public class TenXSettingsConstants {
    public static final String STATUS_BAR_BATTERY_STYLE = Settings.System.STATUS_BAR_BATTERY_STYLE;
    public static final String QS_BATTERY_STYLE = Settings.System.QS_BATTERY_STYLE;
    public static final String QS_SHOW_BATTERY_PERCENT = Settings.System.QS_SHOW_BATTERY_PERCENT;
    public static final String QS_TILE_UI_STYLE = Settings.System.QS_TILE_UI_STYLE;
    public static final String DEFAULT_QS_TILE_CORNER_RADIUS = Settings.System.DEFAULT_QS_TILE_CORNER_RADIUS;
    public static final String DEFAULT_QS_TILE_STYLES = Settings.System.DEFAULT_QS_TILE_STYLES;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_SHOWN = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_SHOWN;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_ARROW = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_ARROW;
    public static final String SETTINGS_DASHBOARD_ARROW_COLOR = Settings.System.SETTINGS_DASHBOARD_ARROW_COLOR;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_STYLE = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_STYLE;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_COLOR = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_COLOR;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_STROKE_WIDTH = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_STROKE_WIDTH;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_GRADIENT_START_COLOR = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_GRADIENT_START_COLOR;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_GRADIENT_END_COLOR = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_GRADIENT_END_COLOR;
    public static final String SETTINGS_DASHBOARD_ICON_COLOR = Settings.System.SETTINGS_DASHBOARD_ICON_COLOR;
    public static final String SETTINGS_DASHBOARD_IOCON_STYLES = Settings.System.SETTINGS_DASHBOARD_IOCON_STYLES;
    public static final String SETTINGS_DASHBOARD_BACKGROUND_SIZE = Settings.System.SETTINGS_DASHBOARD_BACKGROUND_SIZE;
    public static final String USE_CUSTOM_STATUSBAR_PADDING_START = Settings.System.USE_CUSTOM_STATUSBAR_PADDING_START;
    public static final String CUSTOM_STATUSBAR_PADDING_START = Settings.System.CUSTOM_STATUSBAR_PADDING_START;
    public static final String USE_CUSTOM_STATUSBAR_PADDING_END = Settings.System.USE_CUSTOM_STATUSBAR_PADDING_END;
    public static final String CUSTOM_STATUSBAR_PADDING_END = Settings.System.CUSTOM_STATUSBAR_PADDING_END;
    public static final String USE_CUSTOM_STATUSBAR_HEIGHT = Settings.System.USE_CUSTOM_STATUSBAR_HEIGHT;
    public static final String CUSTOM_STATUSBAR_HEIGHT = Settings.System.CUSTOM_STATUSBAR_HEIGHT;
    public static final String USE_DUAL_STATUSBAR_MOD = Settings.System.USE_DUAL_STATUSBAR_MOD;
    public static final String SETTINGS_TENX_DASHBOARD_ENABLED = Settings.System.SETTINGS_TENX_DASHBOARD_ENABLED;
    public static final String SETTINGS_TENX_DASHBOARD_BACKGROUND = Settings.System.SETTINGS_TENX_DASHBOARD_BACKGROUND;
    public static final String SETTINGS_TENX_DASHBOARD_BACKGROUND_BLUR = Settings.System.SETTINGS_TENX_DASHBOARD_BACKGROUND_BLUR;
    public static final String SETTINGS_TENX_DASHBOARD_CUSTOM_NAME = Settings.System.SETTINGS_TENX_DASHBOARD_CUSTOM_NAME;
    public static final String SETTINGS_TENX_DASHBOARD_SUMMARY_TYPE = Settings.System.SETTINGS_TENX_DASHBOARD_SUMMARY_TYPE;
    public static final String SETTINGS_TENX_DASHBOARD_DATA_USAGE = Settings.System.SETTINGS_TENX_DASHBOARD_DATA_USAGE;
    public static final String SETTINGS_TENX_DASHBOARD_BATTERY_BAR = Settings.System.SETTINGS_TENX_DASHBOARD_BATTERY_BAR;
    public static final String SETTINGS_TENX_DASHBOARD_ROUND_IMAGE_RADIUS = Settings.System.SETTINGS_TENX_DASHBOARD_ROUND_IMAGE_RADIUS;
    public static final String SETTINGS_TENX_DASHBOARD_IMAGE_ALPHA = Settings.System.SETTINGS_TENX_DASHBOARD_IMAGE_ALPHA;
    public static final String SETTINGS_TENX_DASHBOARD_WEATHER_TYPE = Settings.System.SETTINGS_TENX_DASHBOARD_WEATHER_TYPE;
    public static final String SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR = Settings.System.SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR;
    public static final String SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_EIGHTY = Settings.System.SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_EIGHTY;
    public static final String SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_SIXTY = Settings.System.SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_SIXTY;
    public static final String SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_FOURTY = Settings.System.SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_FOURTY;
    public static final String SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_TWENTY = Settings.System.SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_TWENTY;
    public static final String SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_ALPHA = Settings.System.SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_ALPHA;

    public static final String[] SYSTEM_SETTINGS_KEYS = {
        STATUS_BAR_BATTERY_STYLE,
        QS_BATTERY_STYLE,
        QS_SHOW_BATTERY_PERCENT,
        QS_TILE_UI_STYLE,
        SETTINGS_DASHBOARD_BACKGROUND_SHOWN,
        SETTINGS_DASHBOARD_BACKGROUND_ARROW,
        SETTINGS_DASHBOARD_ARROW_COLOR,
        SETTINGS_DASHBOARD_BACKGROUND_STYLE,
        SETTINGS_DASHBOARD_BACKGROUND_COLOR,
        SETTINGS_DASHBOARD_BACKGROUND_STROKE_WIDTH,
        SETTINGS_DASHBOARD_BACKGROUND_GRADIENT_START_COLOR,
        SETTINGS_DASHBOARD_BACKGROUND_GRADIENT_END_COLOR,
        SETTINGS_DASHBOARD_ICON_COLOR,
        SETTINGS_DASHBOARD_IOCON_STYLES,
        SETTINGS_DASHBOARD_BACKGROUND_SIZE,
        USE_CUSTOM_STATUSBAR_PADDING_START,
        CUSTOM_STATUSBAR_PADDING_START,
        USE_CUSTOM_STATUSBAR_PADDING_END,
        CUSTOM_STATUSBAR_PADDING_END,
        USE_CUSTOM_STATUSBAR_HEIGHT,
        CUSTOM_STATUSBAR_HEIGHT,
        USE_DUAL_STATUSBAR_MOD,
        SETTINGS_TENX_DASHBOARD_ENABLED,
        SETTINGS_TENX_DASHBOARD_BACKGROUND,
        SETTINGS_TENX_DASHBOARD_BACKGROUND_BLUR,
        SETTINGS_TENX_DASHBOARD_CUSTOM_NAME,
        SETTINGS_TENX_DASHBOARD_SUMMARY_TYPE,
        SETTINGS_TENX_DASHBOARD_DATA_USAGE,
        SETTINGS_TENX_DASHBOARD_BATTERY_BAR,
        SETTINGS_TENX_DASHBOARD_ROUND_IMAGE_RADIUS,
        SETTINGS_TENX_DASHBOARD_IMAGE_ALPHA,
        SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR,
        SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_EIGHTY,
        SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_SIXTY,
        SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_FOURTY,
        SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_TWENTY,
        SETTINGS_TENX_DASHBOARD_BATTERY_LEVEL_COLOR_ALPHA
    };
}
